### ISSUE TITLE
Transfer Bitcoin

### ISSUE THREAD

**Issue by isqan** [rdegges/btc#1]
Hi. I did transfer bitcoin from my Copay account to Xapo Debit Card. Its clearly said that within 30minutes will be confirmed but rite now almost a day i didnt receive the fund from Copay to Xapo Card and its happen like this. Please do advice.

**Comment by rdegges** [comment]
I think you have the wrong project.

**Comment by isqan** [comment]
Then how i wanna ask about the copay system?

**Comment by rdegges** [comment]
This is a command line project for coinbase. If you have a general question about bitcoin, or whatever bank you are using, you might want to try contacting the customer support for your bank! Best luck!
